### ISSUE TITLE
Not working after iteration 0

### ISSUE THREAD

**Issue by anahrendra** [younggyoseo/CaDM#1]
Hi! I cloned this repo and tried to run one of the experiment (Vanilla DM+CaDM). However, it seems like it stuck after iteration 0 and not running anymore. Do you have any idea about this?

Thank you! Have a nice day!

**Comment by anahrendra** [comment]
I just figured out that it is just the iteration is getting slower after iteration 0. Do you have any information about the running time on your computing environment?

**Comment by younggyoseo** [comment]
Hi.

-As more transitions are stored and used for updating the dynamics model, it is normal that running time for each iteration is getting longer. Have you checked the GPU utilization while running experiments?

-In my experience, it takes a lot of time for running evaluation (after finishing iteration), but not for training dynamics model.

-I don't have a logging that shows the running time for experiments, but as a rough estimate (as far as I remember), it might take 10~12 hours for reproducing the results in the paper while using titan XP.

I'll let you know if I find the logs.

**Comment by younggyoseo** [comment]
Found that several works based on our paper successfully run their own experiments using this codebase. closing this issue.
